apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSAiZ2hjci5pbyI6IHsKICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJjM2RsWlhSc1lXNDZaMmh3WDFOUk5XUXhTVmR5ZVZWdE5tUk9hRk0yYldWeWVVSlNObVpEY25rd2J6SlhXSGhIT0E9PSIKICAgIH0KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9
type: kubernetes.io/dockerconfigjson
